name: proj
channels:
  - bioconda
  - conda-forge
  - colomoto
  - defaults
dependencies:
  - deap
  - jupyter
  - keras<2
  - librosa
  - matplotlib
  - mutagen
  - numpy
  - pandas
  - pydot
  - python=3
  - python-dotenv
  - requests
  - seaborn
  - scikit-learn
  - scipy
  - sympy
  - tensorflow-gpu
  - tqdm
